import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { generateAdaptiveLearningPath } from '@/services/adaptiveLearningPathService';
import type { AdaptiveLearningPathData, LearningPathStep } from '@/services/adaptiveLearningPathService';
import { useAuth } from '@/context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { 
  Sparkles, 
  Flame, 
  CheckCircle2, 
  ArrowRight, 
  RefreshCw, 
  Clock, 
  TrendingUp, 
  AlertTriangle, 
  BookOpen, 
  Play 
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';

export const AdaptiveLearningPathWidget: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [data, setData] = useState<AdaptiveLearningPathData | null>(null);
  const [selectedSubjectFilter, setSelectedSubjectFilter] = useState<string>('all');
  const [isGenerating, setIsGenerating] = useState(false);

  const loadPath = async (subjFilter?: string) => {
    setIsGenerating(true);
    const path = await generateAdaptiveLearningPath(user?.id, subjFilter || selectedSubjectFilter);
    setData(path);
    setIsGenerating(false);
  };

  useEffect(() => {
    loadPath();
  }, [user?.id]);

  const handleFilterChange = (subj: string) => {
    setSelectedSubjectFilter(subj);
    loadPath(subj);
  };

  const handleToggleStepComplete = (stepId: string) => {
    if (!data) return;
    const updatedSteps = data.steps.map((s) => {
      if (s.id === stepId) {
        const nextState = !s.isCompleted;
        if (nextState) toast.success(`Step ${s.stepNumber} completed! Keep going!`);
        return { ...s, isCompleted: nextState };
      }
      return s;
    });

    const completedCount = updatedSteps.filter((s) => s.isCompleted).length;
    setData({
      ...data,
      completedStepsCount: completedCount,
      steps: updatedSteps
    });
  };

  const handleLaunchStep = (step: LearningPathStep) => {
    navigate(`/practice?subject=${encodeURIComponent(step.practiceSubjectParam)}&topic=${encodeURIComponent(step.topicName)}`);
  };

  if (isGenerating && !data) {
    return (
      <div className="p-8 flex flex-col items-center justify-center min-h-[300px] bg-card border border-border rounded-2xl shadow-sm">
        <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4" />
        <p className="text-sm text-muted-foreground font-medium">Analyzing practice history and generating custom learning path...</p>
      </div>
    );
  }

  if (!data || !data.hasSufficientData || data.steps.length === 0) {
    return (
      <div className="p-8 flex flex-col items-center justify-center min-h-[300px] bg-card border border-border rounded-2xl shadow-sm text-center">
        <div className="w-12 h-12 rounded-2xl bg-primary/10 text-primary flex items-center justify-center mb-3">
          <BookOpen className="w-6 h-6" />
        </div>
        <h3 className="text-lg font-bold text-foreground mb-1">No Practice History Recorded Yet</h3>
        <p className="text-sm text-muted-foreground max-w-md mb-6">
          Complete your first practice sessions or mock exams so the adaptive engine can analyze your performance and build your personalized learning path.
        </p>
        <Button onClick={() => navigate('/practice')} className="font-bold gap-2">
          <Play className="w-4 h-4" /> Start Practice Session
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Widget Header & Metrics */}
      <div className="bg-card border border-border rounded-2xl p-6 shadow-sm flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Badge className="bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30">
              <Flame className="w-3.5 h-3.5 mr-1" /> Dynamic Learning Path
            </Badge>
            <span className="text-xs text-muted-foreground font-medium">Updated: {data.generatedAt}</span>
          </div>
          <h2 className="text-2xl font-bold font-display tracking-tight text-foreground">
            Adaptive Learning Path
          </h2>
          <p className="text-sm text-muted-foreground max-w-xl">
            Custom sequence automatically generated by analyzing your weak areas. Complete each step to steadily raise your overall score.
          </p>
        </div>

        {/* Quick Summary Metrics */}
        <div className="flex flex-wrap items-center gap-4 bg-muted/30 p-4 rounded-xl border border-border w-full lg:w-auto shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold">
              <TrendingUp className="w-5 h-5" />
            </div>
            <div>
              <div className="text-[11px] text-muted-foreground uppercase font-bold tracking-wider">Potential Gain</div>
              <div className="text-base font-bold font-mono text-emerald-600 dark:text-emerald-400">
                +{data.potentialScoreGain} UTME Pts
              </div>
            </div>
          </div>

          <div className="h-8 w-px bg-border hidden sm:block" />

          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-500 flex items-center justify-center font-bold">
              <Clock className="w-5 h-5" />
            </div>
            <div>
              <div className="text-[11px] text-muted-foreground uppercase font-bold tracking-wider">Est. Study Time</div>
              <div className="text-base font-bold font-mono text-foreground">
                {data.estimatedTotalMinutes} Minutes
              </div>
            </div>
          </div>

          <Button
            variant="outline"
            size="sm"
            onClick={() => loadPath()}
            disabled={isGenerating}
            className="ml-auto font-bold flex items-center gap-1.5"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
            <span>Recalculate</span>
          </Button>
        </div>
      </div>

      {/* Subject Filter Pills */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none">
        {['all', 'Use of English', 'Mathematics', 'Physics', 'Chemistry', 'Biology'].map((subj) => (
          <button
            key={subj}
            onClick={() => handleFilterChange(subj)}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap shrink-0 border ${
              selectedSubjectFilter === subj
                ? 'bg-primary text-primary-foreground border-primary shadow-sm'
                : 'bg-card text-muted-foreground border-border hover:bg-muted'
            }`}
          >
            {subj === 'all' ? 'All Subjects' : subj}
          </button>
        ))}
      </div>

      {/* Steps List Timeline */}
      <div className="space-y-4">
        {data.steps.map((step, idx) => {
          const isCritical = step.priorityLevel === 'CRITICAL';
          const isHigh = step.priorityLevel === 'HIGH';

          return (
            <motion.div
              key={step.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: idx * 0.05 }}
              className={`p-5 rounded-2xl border transition-all shadow-sm ${
                step.isCompleted
                  ? 'bg-muted/30 border-border opacity-75'
                  : isCritical
                  ? 'bg-rose-500/5 border-rose-500/30 hover:border-rose-500/60'
                  : isHigh
                  ? 'bg-amber-500/5 border-amber-500/30 hover:border-amber-500/60'
                  : 'bg-card border-border hover:border-primary/50'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="flex items-start gap-4">
                  {/* Step Number Circle / Completion Checkbox */}
                  <button
                    onClick={() => handleToggleStepComplete(step.id)}
                    className={`w-10 h-10 rounded-xl flex items-center justify-center font-bold text-sm shrink-0 transition-transform hover:scale-105 ${
                      step.isCompleted
                        ? 'bg-emerald-500 text-white shadow-sm'
                        : isCritical
                        ? 'bg-rose-500 text-white'
                        : 'bg-primary/10 text-primary border border-primary/30'
                    }`}
                  >
                    {step.isCompleted ? (
                      <CheckCircle2 className="w-5 h-5" />
                    ) : (
                      <span>{step.stepNumber}</span>
                    )}
                  </button>

                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge variant="outline" className="text-[10px] font-mono">
                        {step.subjectName}
                      </Badge>
                      <Badge className={`text-[10px] border-none font-bold ${
                        isCritical
                          ? 'bg-rose-500/20 text-rose-600 dark:text-rose-400'
                          : isHigh
                          ? 'bg-amber-500/20 text-amber-600 dark:text-amber-400'
                          : 'bg-primary/20 text-primary'
                      }`}>
                        {step.priorityLevel} PRIORITY
                      </Badge>
                      <span className="text-xs text-muted-foreground font-mono">
                        {step.estimatedMinutes} Mins
                      </span>
                    </div>

                    <h3 className="text-base font-bold text-foreground font-display">
                      {step.topicName}
                    </h3>
                    <p className="text-xs text-muted-foreground">
                      {step.learningReason}
                    </p>
                  </div>
                </div>

                {/* Right Side Action Button */}
                <div className="flex items-center gap-3 shrink-0 self-end sm:self-center">
                  <div className="text-right hidden md:block">
                    <div className="text-[11px] text-muted-foreground">Current Accuracy</div>
                    <div className="text-sm font-bold font-mono text-foreground">{step.currentAccuracy}%</div>
                  </div>
                  <Button
                    onClick={() => handleLaunchStep(step)}
                    size="sm"
                    className="bg-primary text-primary-foreground font-bold flex items-center gap-2 shadow-sm"
                  >
                    <Play className="w-3.5 h-3.5 fill-current" /> Launch Step Drill
                  </Button>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
};
