/**
 * Utility functions for cleaning and formatting CBT questions and options.
 * Ensures questions imported from CSVs, past question PDFs, or scraped data
 * do not show leading question numbers (e.g., "1. ", "15. ", "Question 10: ", "JAMB 2018 Q4: ")
 * so that all questions feel natively generated by Scholars Resort CBT Bank.
 */

export function cleanQuestionText(text: string | null | undefined): string {
  if (!text) return '';

  let cleaned = text.trim();

  // Remove HTML tags if present (e.g., <p>, <br>)
  cleaned = cleaned.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();

  // 1. Remove exam year / prefix tags e.g. "JAMB 2018 Q4: ", "UTME 2020 Question 12 - ", "WAEC 2019 #5: "
  cleaned = cleaned.replace(/^(?:(?:jamb|utme|waec|neco|pq|scholars)\s*(?:\d{4})?\s*)?(?:question|q)?\s*\[?\d+\]?\s*[\.\:\)\-\s]+\s*/i, '');

  // 2. Remove leading question numbers e.g. "1. ", "15. ", "10) ", "100 - "
  cleaned = cleaned.replace(/^\d+[\.\:\)]\s*/, '');

  // 3. Remove "Question 12: " or "Q12. "
  cleaned = cleaned.replace(/^(?:question|q)\s*\d+\s*[\.\:\-]\s*/i, '');

  cleaned = cleaned.trim();

  // Capitalize first letter if lowercase
  if (cleaned.length > 0) {
    cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  }

  return cleaned;
}

export function cleanOptionText(text: string | null | undefined): string {
  if (!text) return '';

  let cleaned = text.trim();

  // Remove HTML tags if present
  cleaned = cleaned.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();

  // Remove option letter prefixes like "A. ", "A) ", "a. ", "(A) "
  cleaned = cleaned.replace(/^\(?\s*[a-eA-E]\s*[\)\.\:\-]\s*/, '').trim();

  if (cleaned.length > 0) {
    cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  }

  return cleaned;
}
