-- Migration 0031: Enterprise Tournament Fields
ALTER TABLE public.tournaments
ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS invite_code TEXT,
ADD COLUMN IF NOT EXISTS password TEXT,
ADD COLUMN IF NOT EXISTS min_players INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_players INTEGER DEFAULT 1000,
ADD COLUMN IF NOT EXISTS coin_reward INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS xp_reward INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS badge_reward TEXT,
ADD COLUMN IF NOT EXISTS difficulty TEXT DEFAULT 'mixed',
ADD COLUMN IF NOT EXISTS question_source TEXT DEFAULT 'mixed';
